### ISSUE TITLE
Help with Digi Hungary

### ISSUE THREAD

**Issue by gurabli** [dexterke/plugin.video.digi-online#4]
Hi,
could you please help me how can I adapt this addon to work with Digi Hungary Online? 
Thanks

**Comment by dexterke** [comment]
Helló, 
Szívesen segítek, angolul szeretnék írni mivel nem ismerem a magyar szakkifejezéseket.Küld el kérlek a DIGI-Online Magyar honlap cimét, várom kérdéseidet.
    On Tuesday, August 14, 2018, 4:40:14 PM GMT+1, gurabli <notifications@github.com> wrote:  
 
 
Hi,
could you please help me how can I adapt this addon to work with Digi Hungary Online?
Thanks

**Comment by gurabli** [comment]
Hello,
köszönöm szépen válaszod! Persze, mehet angolul.
The address for Digi Online Hungary is: http://digionline.hu/
I'm not sure if the structure of the site is the same as the Romanian version. I'm not good at Kodi addons, so I can't create or adapt this. But it would be so good to have a working Kodi addon for Digi Online Hungary. I would be so much grateful (and many other users for sure) if you help to create one.
I guess you will need access to the online content. Send me an e-mail and I will send you username and pass to access Digi Online Hungary. My email: gurabli at gmail dot com
I hope it can be done.
Thanks

**Comment by dexterke** [comment]
Will do. 
FYI - I'll be away for the next few weeks, gonna be slow to respond (slower than usual).

**Comment by kormi0312** [comment]
Hi,

I have just found this thread and I'm wondering if there is a progress in this case or I just missed something?
I can also provide access to Hungarian digi online if I can support this project.
Thank in advance for your help in advance!

**Comment by dexterke** [comment]
There is no progress of any sorts at the moment. Emailed gurabli in private, still waiting for him to reply.

**Comment by dexterke** [comment]
Please note that the plugin cannot play the Digi.ro  TV programmes that have DRM encryption (HBO, HBO2, HBO3,DIGI FILM, CINEMAX, CINEMAX 2), documented in the changelog file.

**Comment by kormi0312** [comment]
It would be great if you could do the same thing with hungarian digi online like romanian.
I have already created a password for you to get access to Hungarian digi online. If you can give me your email address I would send you the details.
Thanks again for your help!

**Comment by kormi0312** [comment]
kormi0312 kukac gmail pont com. Thanks a lot! (Köszönöm szépen előre is a segítséged!)

**Comment by fuligjimmy** [comment]
hi, could you please share with me as well? tothjozsi kukac start pont pt

köszi! :)

**Comment by dexterke** [comment]
@fuligjimmy
I'm working (in my spare time) on figuring out the way the web platform works, whatever solution I will find (if any) will be made public just like this one here.

**Comment by dexterke** [comment]
voilà: https://github.com/dexterke/plugin.video.digi.hu-online
